Name: "CI Workflow"
on:
  push:
    branches:
      - main
  workflow_dispatch:
   inputs:
     environment:
       description: 'Environment to deploy to'
       required: true
       type: choice
       options:
         - dev 
         - staging
         - production
     deployment:
       description: 'Deployment type'
       required: false
       type: boolean
